/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "language.switch": [
        {
            "name": "locale",
            "required": true
        }
    ],
    "get-started": [],
    "otp.view": [],
    "otp.verify": [],
    "otp.resend": [],
    "dashboard": [],
    "rmd.index": [],
    "rmd.intro": [],
    "rmd.profile": [],
    "rmd.profile.store": [],
    "rmd.gods-purpose": [],
    "rmd.what-the-bible-says": [],
    "rmd.what-the-bible-says.store": [],
    "rmd.true-success": [],
    "rmd.true-success.store": [],
    "rmd.the-only-one": [],
    "rmd.the-only-one.store": [],
    "rmd.the-only-one-meeting-2": [],
    "rmd.the-only-one-meeting-2.store": [],
    "rmd.the-only-one-meeting-3": [],
    "rmd.the-only-one-meeting-3.store": [],
    "rmd.career-exploration": [],
    "rmd.career-exploration.store": [],
    "rmd.career-exploration-p2": [],
    "rmd.career-exploration-p2.store": [],
    "rmd.preparation-dream-island": [],
    "rmd.preparation-dream-island.store": [],
    "rmd.files.upload": [],
    "rmd.chapters": [],
    "api.admin.schedules.index": [],
    "rmd.dashboard": [],
    "rmd.dashboard.ppa-info": [],
    "health-screenings.index": [],
    "health-screenings.create": [],
    "health-screenings.store": [],
    "health-screenings.show": [
        {
            "name": "health_screening",
            "required": true
        }
    ],
    "health-screenings.edit": [
        {
            "name": "health_screening",
            "required": true
        }
    ],
    "health-screenings.update": [
        {
            "name": "health_screening",
            "required": true
        }
    ],
    "health-screenings.destroy": [
        {
            "name": "health_screening",
            "required": true
        }
    ],
    "api.health-screenings.participants": [],
    "health-screenings.export-pdf": [
        {
            "name": "health_screening",
            "required": true
        }
    ],
    "notifications.read": [
        {
            "name": "id",
            "required": true
        }
    ],
    "mentors.index": [],
    "mentors.create": [],
    "mentors.store": [],
    "mentors.edit": [
        {
            "name": "mentor",
            "required": true,
            "binding": "id"
        }
    ],
    "mentors.update": [
        {
            "name": "mentor",
            "required": true,
            "binding": "id"
        }
    ],
    "mentors.toggle-status": [
        {
            "name": "mentor",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.create": [],
    "participants.store": [],
    "participants.edit": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.attendance.sessions": [],
    "api.admin.attendance.deactivate": [
        {
            "name": "session",
            "required": true
        }
    ],
    "api.admin.attendance.resend-email": [
        {
            "name": "session",
            "required": true
        }
    ],
    "admin.attendance.qr-display": [],
    "api.admin.attendance.active-sessions": [],
    "admin.attendance.monitor": [],
    "participants.update": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.toggle-status": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.assign-mentor": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.destroy": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "schedule.index": [],
    "schedule.store": [],
    "schedule.update": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "schedule.destroy": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "rmd-report.export.excel": [],
    "admin.mentor-performance.index": [],
    "rmd-report.export.pdf": [],
    "rmd-report.export.analytics": [],
    "admin.profile-photos.index": [],
    "admin.profile-photos.upload": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.profile-photos.approve": [
        {
            "name": "photoRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.profile-photos.reject": [
        {
            "name": "photoRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.profile-photos.request-reupload": [
        {
            "name": "photoRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.profile-photos.bulk-approve": [],
    "admin.profile-photos.bulk-reject": [],
    "admin.profile-photos.export": [],
    "admin.profile-photos.bulk-upload-csv": [],
    "api.admin.profile-photos.pending": [],
    "api.admin.schedule-messages.unread": [],
    "api.admin.schedule-messages.read": [
        {
            "name": "message",
            "required": true,
            "binding": "id"
        }
    ],
    "api.admin.schedule-messages.archive": [
        {
            "name": "message",
            "required": true,
            "binding": "id"
        }
    ],
    "api.admins.index": [],
    "api.admins.store": [],
    "api.admins.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.admins.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.admins.toggle-status": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.schedule-approval.index": [],
    "api.admin.schedules.pending": [],
    "api.admin.schedules.all": [],
    "api.admin.schedules.details": [
        {
            "name": "meeting",
            "required": true,
            "binding": "id"
        }
    ],
    "api.admin.general-meeting-dates.toggle": [],
    "api.admin.schedules.approve": [
        {
            "name": "meeting",
            "required": true,
            "binding": "id"
        }
    ],
    "api.admin.schedules.reject": [
        {
            "name": "meeting",
            "required": true,
            "binding": "id"
        }
    ],
    "api.admin.schedules.request-modification": [
        {
            "name": "meeting",
            "required": true,
            "binding": "id"
        }
    ],
    "api.admin.schedules.bulk-approve": [],
    "api.admin.schedules.bulk-reject": [],
    "api.admin.notifications.schedule-approvals": [],
    "api.admin.notifications.read": [
        {
            "name": "notificationId",
            "required": true
        }
    ],
    "api.admin.schedules.deletion-requests": [],
    "api.admin.schedules.approve-deletion": [
        {
            "name": "meeting",
            "required": true,
            "binding": "id"
        }
    ],
    "api.admin.schedules.reject-deletion": [
        {
            "name": "meeting",
            "required": true,
            "binding": "id"
        }
    ],
    "api.notifications.unread": [],
    "gifts.verify": [
        {
            "name": "gift",
            "required": true,
            "binding": "id"
        }
    ],
    "gifts.log-view": [
        {
            "name": "gift",
            "required": true,
            "binding": "id"
        }
    ],
    "gifts.create": [],
    "gifts.store": [],
    "gifts.edit": [
        {
            "name": "gift",
            "required": true,
            "binding": "id"
        }
    ],
    "gifts.update": [
        {
            "name": "gift",
            "required": true,
            "binding": "id"
        }
    ],
    "gifts.destroy": [
        {
            "name": "gift",
            "required": true,
            "binding": "id"
        }
    ],
    "gifts.index": [],
    "gifts.upload-proof": [
        {
            "name": "gift",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.index": [],
    "participants.update-log": [],
    "participants.show": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.rmd-summary": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.status.update": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.notes.store": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.tasks.store": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.tasks.update": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.meetings.store": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "communication.index": [],
    "mentor.profile-photo.request": [],
    "rmd-report.index": [],
    "rmd-report.participant.details": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "participant.communication.index": [],
    "participant.profile-photo.request": [],
    "participant.notes": [],
    "participant.schedule": [],
    "api.mentor-documents.index": [],
    "api.mentor-documents.upload": [],
    "api.mentor-documents.download": [
        {
            "name": "document",
            "required": true,
            "binding": "id"
        }
    ],
    "api.admin.mentor-documents.index": [],
    "mentor.schedule": [],
    "api.mentor-schedules": [],
    "api.general-meeting-dates": [],
    "api.mentor-availability.store": [],
    "api.mentor-availability.destroy": [
        {
            "name": "availability",
            "required": true,
            "binding": "id"
        }
    ],
    "api.mentor-meetings.store": [],
    "api.mentor-meetings.update": [
        {
            "name": "meeting",
            "required": true,
            "binding": "id"
        }
    ],
    "api.mentor-meetings.destroy": [
        {
            "name": "meeting",
            "required": true,
            "binding": "id"
        }
    ],
    "api.mentor-schedules.export": [],
    "api.schedules": [],
    "api.schedules.update-priority": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "api.schedule-messages.store": [],
    "api.schedules.messages": [
        {
            "name": "schedule",
            "required": true
        }
    ],
    "api.online-users": [],
    "api.users.search": [],
    "api.chat.global": [],
    "api.chat.index": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.chat.store": [],
    "api.chat.typing": [],
    "api.chat.flag": [
        {
            "name": "message",
            "required": true,
            "binding": "id"
        }
    ],
    "api.chat.read": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.chat.unread-count": [],
    "api.log-error": [],
    "rmd.files.download": [
        {
            "name": "file",
            "required": true,
            "binding": "id"
        }
    ],
    "rmd.files.delete": [
        {
            "name": "file",
            "required": true,
            "binding": "id"
        }
    ],
    "attendance.index": [],
    "attendance.scan": [],
    "attendance.documentation": [
        {
            "name": "attendance",
            "required": true
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
