import { useState, useEffect } from 'react';
import { usePage, router } from '@inertiajs/react';
import { __ } from '@/Utils/lang';
import axios from 'axios';
import TextInput from '@/Components/TextInput';
import PrimaryButton from '@/Components/PrimaryButton';
import SecondaryButton from '@/Components/SecondaryButton';
import Modal from '@/Components/Modal';
import InputLabel from '@/Components/InputLabel';
import InputError from '@/Components/InputError';
import { useForm } from '@inertiajs/react';
import ProfilePhoto from '@/Components/ProfilePhoto';

export default function AdminList() {
    const [admins, setAdmins] = useState({ data: [] });
    const [search, setSearch] = useState('');
    const [loading, setLoading] = useState(false);
    const [editingUser, setEditingUser] = useState(null);
    const { auth } = usePage().props;

    // Form for editing admin
    const { data, setData, patch, processing, errors, reset, clearErrors } = useForm({
        first_name: '',
        last_name: '',
        email: '',
        job_title: '',
        phone_number: '',
    });

    const fetchAdmins = async (url = route('api.admins.index')) => {
        setLoading(true);
        try {
            const params = new URLSearchParams();
            if (search) params.append('search', search);
            if (url.includes('?')) {
                // If url already has params (from pagination links), append search if not present
                // But usually pagination links generated by Laravel include current query params if using withQueryString()
                // Our controller doesn't seem to use withQueryString(), so we might lose search on pagination.
                // Let's rely on the URL passed, but if it's the default, add search.
            } else if (search) {
                url += `?search=${search}`;
            } else {
                 // If url has params, we might need to merge. 
                 // Simple approach: append search to url if it doesn't have it.
                 if (search && !url.includes('search=')) {
                    url += (url.includes('?') ? '&' : '?') + `search=${search}`;
                 }
            }
            
            const response = await axios.get(url);
            setAdmins(response.data);
        } catch (error) {
            console.error('Failed to fetch admins', error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        const timeoutId = setTimeout(() => {
            fetchAdmins();
        }, 300);
        return () => clearTimeout(timeoutId);
    }, [search]);

    const openEditModal = (user) => {
        setEditingUser(user);
        setData({
            first_name: user.first_name || '',
            last_name: user.last_name || '',
            email: user.email || '',
            job_title: user.job_title || '',
            phone_number: user.phone_number || '',
        });
        clearErrors();
    };

    const closeEditModal = () => {
        setEditingUser(null);
        reset();
        clearErrors();
    };

    const submitEdit = (e) => {
        e.preventDefault();
        patch(route('api.admins.update', editingUser.id), {
            onSuccess: () => {
                closeEditModal();
                fetchAdmins();
            },
        });
    };

    const toggleStatus = async (user) => {
        if (user.id === auth.user.id) return;
        
        try {
            await router.patch(route('api.admins.toggle-status', user.id), {}, {
                preserveScroll: true,
                onSuccess: () => fetchAdmins()
            });
        } catch (error) {
            console.error('Failed to toggle status', error);
        }
    };

    const deleteUser = async (user) => {
        if (!confirm(__('Are you sure you want to delete this admin?'))) return;
        
        try {
            await router.delete(route('api.admins.destroy', user.id), {
                preserveScroll: true,
                onSuccess: () => fetchAdmins()
            });
        } catch (error) {
            console.error('Failed to delete user', error);
        }
    };

    return (
        <section className="space-y-6">
            <header>
                <h2 className="text-lg font-medium text-gray-900 dark:text-gray-100">
                    {__('Admin List')}
                </h2>
                <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">
                    {__('Manage registered administrators.')}
                </p>
            </header>

            <div className="flex justify-between items-center">
                <div className="w-full max-w-sm">
                    <TextInput
                        placeholder={__('Search admin...')}
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        className="w-full"
                    />
                </div>
            </div>

            <div className="relative overflow-x-auto shadow-md sm:rounded-lg">
                <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" className="px-6 py-3">{__('Name')}</th>
                            <th scope="col" className="px-6 py-3">{__('Email')}</th>
                            <th scope="col" className="px-6 py-3">{__('Job Title')}</th>
                            <th scope="col" className="px-6 py-3">{__('Status')}</th>
                            <th scope="col" className="px-6 py-3">{__('Registered')}</th>
                            <th scope="col" className="px-6 py-3 text-right">{__('Actions')}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {loading ? (
                            <tr>
                                <td colSpan="6" className="px-6 py-4 text-center">{__('Loading...')}</td>
                            </tr>
                        ) : admins.data.length === 0 ? (
                            <tr>
                                <td colSpan="6" className="px-6 py-4 text-center">{__('No admins found.')}</td>
                            </tr>
                        ) : (
                            admins.data.map((admin) => (
                                <tr key={admin.id} className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                                    <td className="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                                        <div className="flex items-center space-x-2">
                                            <ProfilePhoto 
                                                src={admin.profile_photo_url} 
                                                alt={admin.name} 
                                                className="w-8 h-8 rounded-full object-cover" 
                                                fallbackClassName="w-8 h-8 rounded-full bg-gray-200 dark:bg-gray-700 flex items-center justify-center text-gray-500 font-bold text-xs"
                                                fallback={(admin.name || 'A').charAt(0).toUpperCase()}
                                            />
                                            <span>
                                                {admin.name}
                                                {admin.id === auth.user.id && <span className="ml-2 text-xs text-indigo-600 dark:text-indigo-400">({__('You')})</span>}
                                            </span>
                                        </div>
                                    </td>
                                    <td className="px-6 py-4">{admin.email}</td>
                                    <td className="px-6 py-4">{admin.job_title || '-'}</td>
                                    <td className="px-6 py-4">
                                        <span className={`px-2 py-1 rounded text-xs ${
                                            admin.is_active 
                                                ? 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300' 
                                                : 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300'
                                        }`}>
                                            {admin.is_active ? __('Active') : __('Inactive')}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4">
                                        {new Date(admin.created_at).toLocaleDateString()}
                                    </td>
                                    <td className="px-6 py-4 text-right space-x-2">
                                        {admin.id !== auth.user.id && (
                                            <>
                                                <button 
                                                    onClick={() => openEditModal(admin)}
                                                    className="font-medium text-indigo-600 dark:text-indigo-500 hover:underline"
                                                >
                                                    {__('Edit')}
                                                </button>
                                                <button 
                                                    onClick={() => toggleStatus(admin)}
                                                    className="font-medium text-blue-600 dark:text-blue-500 hover:underline"
                                                >
                                                    {admin.is_active ? __('Deactivate') : __('Activate')}
                                                </button>
                                                <button 
                                                    onClick={() => deleteUser(admin)}
                                                    className="font-medium text-red-600 dark:text-red-500 hover:underline"
                                                >
                                                    {__('Delete')}
                                                </button>
                                            </>
                                        )}
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>

            {admins.links && (
                <div className="flex justify-center mt-4 space-x-1">
                    {admins.links.map((link, i) => (
                        <button
                            key={i}
                            onClick={() => link.url && fetchAdmins(link.url)}
                            dangerouslySetInnerHTML={{ __html: link.label }}
                            className={`px-3 py-1 rounded ${
                                link.active 
                                    ? 'bg-indigo-600 text-white' 
                                    : 'bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700'
                            } ${!link.url ? 'opacity-50 cursor-not-allowed' : ''}`}
                            disabled={!link.url}
                        />
                    ))}
                </div>
            )}

            <Modal show={!!editingUser} onClose={closeEditModal}>
                <form onSubmit={submitEdit} className="p-6">
                    <h2 className="text-lg font-medium text-gray-900 dark:text-gray-100">
                        {__('Edit Admin')}
                    </h2>

                    <div className="mt-6 space-y-6">
                        <div>
                            <InputLabel htmlFor="edit_first_name" value={__('First Name')} />
                            <TextInput
                                id="edit_first_name"
                                value={data.first_name}
                                onChange={(e) => setData('first_name', e.target.value)}
                                className="mt-1 block w-full"
                                required
                            />
                            <InputError message={errors.first_name} className="mt-2" />
                        </div>

                        <div>
                            <InputLabel htmlFor="edit_last_name" value={__('Last Name')} />
                            <TextInput
                                id="edit_last_name"
                                value={data.last_name}
                                onChange={(e) => setData('last_name', e.target.value)}
                                className="mt-1 block w-full"
                            />
                            <InputError message={errors.last_name} className="mt-2" />
                        </div>

                        <div>
                            <InputLabel htmlFor="edit_email" value={__('Email')} />
                            <TextInput
                                id="edit_email"
                                type="email"
                                value={data.email}
                                onChange={(e) => setData('email', e.target.value)}
                                className="mt-1 block w-full"
                                required
                            />
                            <InputError message={errors.email} className="mt-2" />
                        </div>

                        <div>
                            <InputLabel htmlFor="edit_job_title" value={__('Job Title')} />
                            <TextInput
                                id="edit_job_title"
                                value={data.job_title}
                                onChange={(e) => setData('job_title', e.target.value)}
                                className="mt-1 block w-full"
                            />
                            <InputError message={errors.job_title} className="mt-2" />
                        </div>

                        <div>
                            <InputLabel htmlFor="edit_phone_number" value={__('Phone Number')} />
                            <TextInput
                                id="edit_phone_number"
                                value={data.phone_number}
                                onChange={(e) => setData('phone_number', e.target.value)}
                                className="mt-1 block w-full"
                            />
                            <InputError message={errors.phone_number} className="mt-2" />
                        </div>
                    </div>

                    <div className="mt-6 flex justify-end">
                        <SecondaryButton onClick={closeEditModal}>
                            {__('Cancel')}
                        </SecondaryButton>

                        <PrimaryButton className="ml-3" disabled={processing}>
                            {__('Save')}
                        </PrimaryButton>
                    </div>
                </form>
            </Modal>
        </section>
    );
}